server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/movies
        username: root
        password: root
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml

folders:
    locations:
        FILE_ATTACHMENTS:
            folder: /file-attachments
